[tools]
yazi = 'latest'
bottom = 'latest'
fastfetch = 'latest'
neovim = '0.12.2'
tree-sitter = 'latest'
'go:github.com/yz025/tocp' = 'latest'

resvg = 'latest'
ffmpeg = 'latest'
fd = 'latest'
'aqua:ip7z/7zip' = 'latest'
ripgrep = 'latest'
fzf = 'latest'
zoxide = 'latest'
imagemagick = 'latest'

uv = 'latest'

lua-language-server = 'latest'
stylua = 'latest'

zig = '0.16.0'
zls = '0.16.0'

go = 'latest'
'go:golang.org/x/tools/gopls' = 'latest'
'go:github.com/golangci/golangci-lint/cmd/golangci-lint' = 'latest'
goreleaser = 'latest'

rust = 'latest'

arduino-cli = 'latest'

starship = 'latest'
