[general]
import = [ "./alacritty-rasmus.toml" ]

live_config_reload = true

[font]
normal = { family = "monospace", style = "SemiBold" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "SemiBold Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 11.5

[keyboard]
bindings = [
{ key = "c", mods = "Alt", action = "Copy"},
{ key = "v", mods = "Alt", action = "Paste"}
]

[window]
decorations_theme_variant = "Dark"
# alacritty doesn't support this.
# [font.features]
# "*" = ["cv01", "cv02", "cv03", "cv11", "cv12"]

