#!/bin/sh

SRC="$DOTFILES/starship/git_fetch_mtime/main.c"
OUT="$DOTFILES/starship/git_fetch_mtime/git_fetch_mtime"

if git diff --quiet ORIG_HEAD HEAD -- "$SRC"; then
    exit 0
fi

clang "$SRC" -o "$OUT" -O2
