[[pairs]]
src = "$HOME/.config/starship.toml"
dst = "./starship.toml"

[[pairs]]
src = "$HOME/.config/alacritty"
dst = "./alacritty"

[[pairs]]
src = "$HOME/.bashrc.d"
dst = "./bash/.bashrc.d"

[[pairs]]
src = "$HOME/.bashrc"
dst = "./bash/.bashrc"

[[pairs]]
src = "$HOME/Documents/projects/.clang-format"
dst = "./.clang-format"

[[pairs]]
src = "$HOME/.config/nvim"
dst = "./nvim"

[[pairs]]
src = "$HOME/.config/yazi"
dst = "./yazi"

[[pairs]]
src = "$HOME/.config/mise"
dst = "./mise"
