[[pairs]]
src = "$HOME/.config/starship"
dst = "$DOTFILES/fws/starship"

[[pairs]]
src = "$HOME/.config/alacritty"
dst = "$DOTFILES/fws/alacritty"

[[pairs]]
src = "$HOME/.bashrc.d"
dst = "$DOTFILES/fws/bash/.bashrc.d"

[[pairs]]
src = "$HOME/.bashrc"
dst = "$DOTFILES/fws/bash/.bashrc"

[[pairs]]
src = "$HOME/Documents/projects/.clang-format"
dst = "$DOTFILES/fws/.clang-format"

[[pairs]]
src = "$HOME/.config/nvim"
dst = "$DOTFILES/fws/nvim"

[[pairs]]
src = "$HOME/.config/yazi"
dst = "$DOTFILES/fws/yazi"

[[pairs]]
src = "$HOME/.config/mise"
dst = "$DOTFILES/fws/mise"
