[[dotfiles]]
original = "~/.config/starship.toml"
copy = "./starship.toml"

[[dotfiles]]
original = "~/.config/alacritty"
copy = "./alacritty"

[[dotfiles]]
original = "~/.bashrc"
copy = "./.bashrc"

[[dotfiles]]
original = "~/Documents/dev/projects/.clang-format"
copy = "./.clang-format"

[[dotfiles]]
original = "~/.config/nvim"
copy = "./nvim"

[[dotfiles]]
original = "~/.config/yazi"
copy = "./yazi"
