[tools]
neovim = '0.12.2'
tree-sitter = 'latest'

arduino-cli = 'latest'

'npm:bash-language-server' = 'latest'
shfmt = 'latest'

go = 'latest'
'go:golang.org/x/tools/gopls' = 'latest'
'go:github.com/golangci/golangci-lint/cmd/golangci-lint' = 'latest'
goreleaser = 'latest'

lua-language-server = 'latest'
stylua = 'latest'

node = 'latest'

rust = 'latest'

zig = '0.16.0'
zls = '0.16.0'
