[[pairs]]
src = "$HOME/.config/starship"
dst = "$DOTFILES/starship"

[[pairs]]
src = "$HOME/.config/alacritty"
dst = "$DOTFILES/alacritty"

[[pairs]]
src = "$HOME/.bashrc.d"
dst = "$DOTFILES/bash/.bashrc.d"

[[pairs]]
src = "$HOME/.bashrc"
dst = "$DOTFILES/bash/.bashrc"

[[pairs]]
src = "$HOME/Documents/projects/.clang-format"
dst = "$DOTFILES/.clang-format"

[[pairs]]
src = "$HOME/.config/nvim"
dst = "$DOTFILES/nvim"

[[pairs]]
src = "$HOME/.config/yazi"
dst = "$DOTFILES/yazi"

[[pairs]]
src = "$HOME/.config/mise"
dst = "$DOTFILES/mise"

[[pairs]]
src = "$HOME/.config/fontconfig"
dst = "$DOTFILES/fontconfig"

[[pairs]]
src = "../.git/hooks/post-merge"
dst = "$DOTFILES/post-merge"
